

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 861768
 */
public class EditEmployee extends javax.swing.JFrame {

    /**
     * Creates new form EditEmployee
     */
    
    private MyHashTable hashTable;
    
    public EditEmployee() {
        initComponents();

    }

    public void setHashTable(MyHashTable table)
    {
        hashTable = table;
     
    }
    
    public MyHashTable getHashTable()
    {
        return(hashTable);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        employeeTypeGroup = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        employeeNumberInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        findEmployeeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EmployeeNumberLabel = new javax.swing.JLabel();
        employeeNumberField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        workLocationField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deductionRateField = new javax.swing.JTextField();
        partTimeEmployeeButton = new javax.swing.JRadioButton();
        fullTimeEmployeeButton = new javax.swing.JRadioButton();
        EmployeeTypeLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        weeksPerYearField = new javax.swing.JTextField();
        hoursPerWeekField = new javax.swing.JTextField();
        wageField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        annualSalaryField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        title.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        title.setText("EDIT EMPLOYEE");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Find the Employee you'd like to change using the employee number, then edit information.");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Employee Number:");

        findEmployeeButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        findEmployeeButton.setText("SEARCH");
        findEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findEmployeeButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Change the existing values to edit the employee. Remember to save :)");

        EmployeeNumberLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EmployeeNumberLabel.setText("Employee Number:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Employee Name:");

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Gender:");

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setText("Male");
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setText("Female");

        genderButtonGroup.add(otherRadioButton);
        otherRadioButton.setText("Other");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Work Location:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Deduction Rate:");

        deductionRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductionRateFieldActionPerformed(evt);
            }
        });

        employeeTypeGroup.add(partTimeEmployeeButton);
        partTimeEmployeeButton.setText("Part Time Employee");
        partTimeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeEmployeeButtonActionPerformed(evt);
            }
        });

        employeeTypeGroup.add(fullTimeEmployeeButton);
        fullTimeEmployeeButton.setText("Full Time Employee");
        fullTimeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeEmployeeButtonActionPerformed(evt);
            }
        });

        EmployeeTypeLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EmployeeTypeLabel.setText("Employee Type");

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("After Editing your information, simply save.");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Weeks Per Year");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Hours Per Week");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Hourly Wage");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Annual Salary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(title)
                                .addGap(143, 143, 143))
                            .addComponent(saveButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(181, 181, 181))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmployeeTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(partTimeEmployeeButton)
                                .addGap(134, 134, 134)
                                .addComponent(fullTimeEmployeeButton)
                                .addGap(63, 63, 63))
                            .addComponent(employeeNumberInput)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(215, 215, 215)
                                            .addComponent(findEmployeeButton))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(EmployeeNumberLabel)
                                                        .addGap(18, 18, 18))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(31, 31, 31)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7))
                                                    .addGap(58, 58, 58)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(maleRadioButton)
                                                    .addGap(110, 110, 110)
                                                    .addComponent(femaleRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(otherRadioButton))
                                                .addComponent(employeeNumberField)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(workLocationField)
                                                .addComponent(deductionRateField)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                            .addComponent(wageField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(223, 223, 223)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(37, 37, 37)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(weeksPerYearField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                            .addComponent(hoursPerWeekField))
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(annualSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findEmployeeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeNumberLabel)
                    .addComponent(employeeNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleRadioButton)
                        .addComponent(femaleRadioButton)
                        .addComponent(otherRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(workLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(deductionRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullTimeEmployeeButton)
                    .addComponent(EmployeeTypeLabel)
                    .addComponent(partTimeEmployeeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(weeksPerYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hoursPerWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(annualSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(wageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel12)
                .addGap(133, 133, 133))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            hashTable.removeEmployee(Integer.valueOf(employeeNumberInput.getText()));
  //          employeeNumberInput.setText("");
            
            //If they change employee number, then there will be two copies of the dude w/ two different employee numbers.
            
        }
        catch(Exception e){
            System.out.println("Something wrong :C");
        }
        
        
        
        if (fullTimeEmployeeButton.isSelected()){
            //full time employee
            
            FullTimeEmployee employee = new FullTimeEmployee();
            
            employee.setEmployeeNumber(Integer.valueOf(employeeNumberField.getText()));
            employee.setFirstName(firstNameField.getText());
            employee.setLastName(lastNameField.getText());
            
            //getting and setting gender
            if (maleRadioButton.isSelected()){
                employee.setGender(0);
            }
            else if (femaleRadioButton.isSelected()){
                employee.setGender(1);
            }
            else{
                employee.setGender(2);
            }
        
            //getting and setting work location
            if (workLocationField.getText().equals("Toronto")){
                employee.setWorkLocation(1);
            }
            else if (workLocationField.getText().equals("Mississauga")){
                employee.setWorkLocation(2);
            }
            else if (workLocationField.getText().equals("New York")){
                employee.setWorkLocation(3);
            }
            else{
                employee.setWorkLocation(0);
            }
        
            
            employee.setAnnualSalary(Double.valueOf(annualSalaryField.getText()));
            
            if (hashTable.isInTable(employee.getEmployeeNumber()) == false){
                hashTable.addEmployee(employee);
            }
        }
        
        else if (partTimeEmployeeButton.isSelected()){
            
            PartTimeEmployee employee = new PartTimeEmployee();
            
            employee.setEmployeeNumber(Integer.valueOf(employeeNumberField.getText()));
            employee.setFirstName(firstNameField.getText());
            employee.setLastName(lastNameField.getText());
            
            
            if (maleRadioButton.isSelected()){
                employee.setGender(0);
            }
            else if (femaleRadioButton.isSelected()){
                employee.setGender(1);
            }
            else{
                employee.setGender(2);
            }
                    
            if (workLocationField.getText().equals("Toronto")){
                employee.setWorkLocation(1);
            }
            else if (workLocationField.getText().equals("Mississauga")){
                employee.setWorkLocation(2);
            }
            else if (workLocationField.getText().equals("New York")){
                employee.setWorkLocation(3);
            }
            else{
                employee.setWorkLocation(0);
            }
            
            employee.setDeductionRate(Double.valueOf(deductionRateField.getText()));
            employee.setHourlyWage(Double.valueOf(wageField.getText()));
            employee.setHoursPerWeek(Double.valueOf(hoursPerWeekField.getText()));
            employee.setWeeksPerYear(Double.valueOf(weeksPerYearField.getText()));
        
            
            if (hashTable.isInTable(employee.getEmployeeNumber()) == false){
                hashTable.addEmployee(employee);
            }
        }
      
   
        
        
        
        
        if (saveButton.getText().equals("CONFIRM")){
           
            hashTable.saveToFile();
            saveButton.setText("SAVE");
            System.out.println("Saved to file.");
        }
        
        else if(saveButton.getText().equals("SAVE")){
            saveButton.setText("CONFIRM");
        }
         
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void findEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findEmployeeButtonActionPerformed
        // TODO add your handling code here:
        
        EmployeeInfo employee; 
        int searchedEmployeeNum = Integer.valueOf(employeeNumberInput.getText());
        
        employee = hashTable.findEmployee(searchedEmployeeNum);

       
        
        
        employeeNumberField.setText(String.valueOf(employee.getEmployeeNumber()));
        firstNameField.setText(employee.getFirstName());
        lastNameField.setText(employee.getLastName());
        
        String gender = "";
        switch(employee.getGender()){
                    case 0:
                        gender = "Male";
                        maleRadioButton.setSelected(true);
                        break;
                        
                    case 1:
                        gender = "Female"; 
                        femaleRadioButton.setSelected(true);
                        break;
                        
                    default:
                        gender = "Other";
                        otherRadioButton.setSelected(true);
                        break;
       
                }
        
        
 
                switch(employee.getWorkLocation())
                {
                    case 0:
                        workLocationField.setText("Other");
                        break;
                        
                    case 1:
                        workLocationField.setText("Toronto");
                        break;
                        
                    case 2:
                        workLocationField.setText("Mississauga");
                        break;
                        
                    case 3:
                        workLocationField.setText("New York");
                        break;
                }

        deductionRateField.setText(String.valueOf(employee.getDeductionRate()));
        
     
        if (employee instanceof FullTimeEmployee){
            
            FullTimeEmployee emp = (FullTimeEmployee) employee;
            
            fullTimeEmployeeButton.setSelected(true);
            annualSalaryField.setText(String.valueOf(emp.getAnnualSalary()));
        }

        else if(employee instanceof PartTimeEmployee){
            PartTimeEmployee emp = (PartTimeEmployee) employee;
            
            partTimeEmployeeButton.setSelected(true);
            
            wageField.setText(String.valueOf(emp.getHourlyWage()));
            hoursPerWeekField.setText(String.valueOf(emp.getHoursPerWeek()));
            weeksPerYearField.setText(String.valueOf(emp.getWeeksPerYear()));
            
        }
        
        
        
  /*       
        int EmployeeNumber = employee.getEmployeeNumber();
        
        if (EmployeeNumber != searchedEmployeeNum){
                
            hashTable.removeEmployee(searchedEmployeeNum);       //remove employee 
            hashTable.addEmployee(employee);
        
        }
  */  
        
        
        
        // TO DO
        // Add functionality for changing employee number without having two copies of the same guy
        // Add functionality for changing employee from Part Time to Full time and Vice Versa 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_findEmployeeButtonActionPerformed

    private void deductionRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductionRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deductionRateFieldActionPerformed

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonActionPerformed

    private void partTimeEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeEmployeeButtonActionPerformed
        // TODO add your handling code here:
        
        //block the full time employee stuff
        annualSalaryField.setText("");
        
    }//GEN-LAST:event_partTimeEmployeeButtonActionPerformed

    private void fullTimeEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeEmployeeButtonActionPerformed
        // TODO add your handling code here:
        
        wageField.setText("");
        hoursPerWeekField.setText("");
        weeksPerYearField.setText("");
        
    }//GEN-LAST:event_fullTimeEmployeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeNumberLabel;
    private javax.swing.JLabel EmployeeTypeLabel;
    private javax.swing.JTextField annualSalaryField;
    private javax.swing.JTextField deductionRateField;
    private javax.swing.JTextField employeeNumberField;
    private javax.swing.JTextField employeeNumberInput;
    private javax.swing.ButtonGroup employeeTypeGroup;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JButton findEmployeeButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JRadioButton fullTimeEmployeeButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JTextField hoursPerWeekField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JRadioButton partTimeEmployeeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel title;
    private javax.swing.JTextField wageField;
    private javax.swing.JTextField weeksPerYearField;
    private javax.swing.JTextField workLocationField;
    // End of variables declaration//GEN-END:variables
}