/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 861768
 */
public class RemoveEmployeeScreen extends javax.swing.JFrame {

    /**
     * Creates new form RemoveEmployeeScreen
     */
    public RemoveEmployeeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeTypeGroup = new javax.swing.ButtonGroup();
        removeEmployeeLabel = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        partTimeEmployeeButton = new javax.swing.JRadioButton();
        fullTimeEmployeeButton = new javax.swing.JRadioButton();
        employeeNumberInstructionLabel = new javax.swing.JLabel();
        employeeNameInstructionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        removeEmployeeLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        removeEmployeeLabel.setText("Remove Employee");

        instructionsLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        instructionsLabel.setText("Please input some Employee Identification Information");

        employeeTypeGroup.add(partTimeEmployeeButton);
        partTimeEmployeeButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        partTimeEmployeeButton.setText("Part Time Employee");

        employeeTypeGroup.add(fullTimeEmployeeButton);
        fullTimeEmployeeButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        fullTimeEmployeeButton.setText("Full Time Employee");

        employeeNumberInstructionLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        employeeNumberInstructionLabel.setText("Employee Number:");

        employeeNameInstructionLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        employeeNameInstructionLabel.setText("Employee Name:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("REDUNDANT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeNameInstructionLabel)
                            .addComponent(employeeNumberInstructionLabel)
                            .addComponent(fullTimeEmployeeButton)
                            .addComponent(partTimeEmployeeButton)
                            .addComponent(instructionsLabel)
                            .addComponent(removeEmployeeLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(removeEmployeeLabel)
                .addGap(18, 18, 18)
                .addComponent(instructionsLabel)
                .addGap(18, 18, 18)
                .addComponent(partTimeEmployeeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullTimeEmployeeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeNumberInstructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeNameInstructionLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveEmployeeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel employeeNameInstructionLabel;
    private javax.swing.JLabel employeeNumberInstructionLabel;
    private javax.swing.ButtonGroup employeeTypeGroup;
    private javax.swing.JRadioButton fullTimeEmployeeButton;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton partTimeEmployeeButton;
    private javax.swing.JLabel removeEmployeeLabel;
    // End of variables declaration//GEN-END:variables
}